name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ env.NVMRC }}
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run test
      - name: Check TypeScript types
        run: npm run check-types
      - name: Check Prettier code style
        run: npm run check-prettier
